Upload the dataset

Import numpy as np, pandas as pd and tensorflow as tf

In [ ]:
# import numpy, matplotlib, pandas
import numpy as np
import pandas as pd
import tensorflow as tf

Read the dataset, observe its five rows, leave redundant columns and make x and y

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y = dataset['Exited'].values
print(X)
print(y)
dataset.head()

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

Data Preprocessing

Encoding categorical data using Lable Encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder
la=LabelEncoder()
X[:,2] = la.fit_transform(X[:,2])
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

One Hot Encoding the "Geography" column using ColumnTransformer and OneHotEncoder

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder= 'passthrough')
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 1.0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 1.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 1.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 1.0, ..., 1, 0, 38190.78]], dtype=object)

Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train ,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0);


Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Building the ANN

In [ ]:
ann = tf.keras.models.Sequential()

Adding the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=5,activation='relu'))

Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=3,activation='relu'))

Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

Compiling the ANN

In [ ]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.6923 - accuracy: 0.5798
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6120 - accuracy: 0.7961
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5745 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5466 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5190 - accuracy: 0.7983
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4870 - accuracy: 0.8144
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4576 - accuracy: 0.8350
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4361 - accuracy: 0.8411
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4205 - accuracy: 0.8421
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4092 - accura

Making the predictions and evaluating the model

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
cm

array([[1519,   76],
       [ 197,  208]])

In [ ]:
accuracy_score(y_test,y_pred)

0.8635